CREATE DATABASE nutri_goal CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE nutri_goal;

-- UTILISATEURS
CREATE TABLE utilisateurs (
  id INT PRIMARY KEY AUTO_INCREMENT,
  nom_complet VARCHAR(100) NOT NULL,
  email VARCHAR(100) UNIQUE NOT NULL,
  mot_de_passe VARCHAR(255) NOT NULL,
  genre ENUM('M', 'F', 'Autre') NOT NULL,
  taille INT NOT NULL COMMENT 'cm',
  poids DECIMAL(5,2) NOT NULL COMMENT 'kg',
  imc DECIMAL(5,2),
  solde DECIMAL(10,2) DEFAULT 0,

  date_inscription TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  date_modification TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

